export const CLICK = 'click'
export const MOUSE_DOWN = 'mousedown'
export const MOUSE_MOVE = 'mousemove'
export const MOUSE_OUT = 'mouseout'
export const MOUSE_OVER = 'mouseover'
export const MOUSE_UP = 'mouseup'
export const MOUSE_WHEEL = 'mousewheel'
export const FOCUS = 'focus'
