export const copyPointEvent = (event: PointerEvent, newName, el: HTMLElement): PointerEvent => {
  return new PointerEvent(newName, {
    altKey: event.altKey,
    bubbles: event.bubbles,
    button: event.button,
    cancelable: event.cancelable,
    clientX: event.clientX,
    clientY: event.clientY,
    ctrlKey: event.ctrlKey,
    composed: event.composed,
    detail: event.detail,
    height: event.height,
    isPrimary: event.isPrimary,
    metaKey: event.metaKey,
    pointerId: event.pointerId,
    pointerType: event.pointerType,
    pressure: event.pressure,
    relatedTarget: el,
    screenX: event.screenX,
    screenY: event.screenY,
    shiftKey: event.shiftKey,
    tangentialPressure: event.tangentialPressure,
    tiltX: event.tiltX,
    tiltY: event.tiltY,
    twist: event.twist,
    view: event.view,
    width: event.width,
  })
}
